### ISSUE TITLE
pgx compatibility

### ISSUE THREAD

**Issue by georgysavva** [cockroachdb/cockroach-go#60]
In my previous [issue](https://github.com/cockroachdb/cockroach-go/issues/59) I was advised to use CockroachDB with the [pgx](https://github.com/jackc/pgx) library. And I started to look deeper into it.
I found out that pgx.Tx isn't compatible with the crdb.Tx interface and I can't use the crdb.ExecuteInTx() function.
I found a wrapper in the main cockroach repo: [here](https://github.com/cockroachdb/cockroach/blob/92495ffb2182671b3338a8c6cd2734cb6de5d392/pkg/workload/pgx_helpers.go#L162-L183)
But it uses very old version of the library, you can see it in the import statement: 
import "github.com/jackc/pgx"
and the current import path is "github.com/jackc/pgx/v4" 
The wrapper wasn't updated in 2 years and calls methods that no longer exist in pgx.

Aside from this incompatibility issue, wouldn't it be better to put those helpers in this repo, instead of the main server repo?

**Comment by andreimatei** [comment]
We used to need to depend on a particular pgx version because of https://github.com/jackc/pgconn/issues/15. But now improvements have been made there, so I think we can now deal with a couple of versions without importing any one.

> Aside from this incompatibility issue, wouldn't it be better to put those helpers in this repo, instead of the main server repo?

Probably. However you can still use pgx with our library in its "driver" mode - so, using pgx through Go's `database/sql` package, not directly (modulo the version comment above). `cockroach-go` is mostly aimed at working with `database/sql`, although its mandate could be extended.

**Comment by georgysavva** [comment]
Thanks for the advise with `database/sql`. I checked how `pgx` integrates with `sql` library and it seems, that `pgx` implementation of the `driver.Tx` doesn't have access to the context on `driver.Tx.Commit()` and `Rollback()`. I opened an issue about that: https://github.com/jackc/pgx/issues/703
It seems we will be able to fix it pretty easily, hence it's not a big deal. But the general advice of the `pgx` maintainer is to use `pgx` natively (not "driver" mode) whenever possible. So supporting last version of `pgx` would be a desirable feature. Thanks!
