### ISSUE TITLE
crdbpgx: compilation error with go modules

### ISSUE THREAD

**Issue by georgysavva** [cockroachdb/cockroach-go#65]
I setup a simple package to try `crdbpgx` with the latest `pgx/v4`. I used go modules to manage my dependencies. I get the following error when trying to compile my package:
```
# github.com/cockroachdb/cockroach-go/crdb/crdbpgx
../../go/pkg/mod/github.com/cockroachdb/cockroach-go@v0.0.0-20200411195601-6f5842749cfc/crdb/crdbpgx/pgx.go:54:21: too many arguments in call to tx.tx.Commit
	have (context.Context)
	want ()
../../go/pkg/mod/github.com/cockroachdb/cockroach-go@v0.0.0-20200411195601-6f5842749cfc/crdb/crdbpgx/pgx.go:58:23: too many arguments in call to tx.tx.Rollback
	have (context.Context)
	want ()
../../go/pkg/mod/github.com/cockroachdb/cockroach-go@v0.0.0-20200411195601-6f5842749cfc/crdb/crdbpgx/pgx.go:63:22: too many arguments in call to tx.tx.Exec
	have (context.Context, string, []interface {}...)
	want (string, ...interface {})
```
Source code of my package: [here](https://github.com/georgysavva/go-tmp/blob/master/tmp_test.go)
The problem occurs because `go mod` also install the previous version of pgx - v3, that is referenced somehow internally. Corresponding part in my `go.sum` file:
```
github.com/jackc/pgx v3.6.2+incompatible h1:2zP5OD7kiyR3xzRYMhOcXVvkDZsImVXfj+yIyTQf3/o=
github.com/jackc/pgx v3.6.2+incompatible/go.mod h1:0ZGrqGqkRlliWnWB4zKnWtjbSWbGkVEFm4TeybAXq+I=
```
I understand that the original problem is with pgx library and when they fix their dependencies the problem will disappear. But maybe it would be beneficial to start using go modules in crdb package to be protected in such cases?

**Comment by georgysavva** [comment]
Hi. Any update on this?

**Comment by andreimatei** [comment]
Looking into it now. This Go modules stuff is over my head; we don't use them yet internally in the main CRDB repo. Let me see what I figure out.

**Comment by andreimatei** [comment]
OK, I've learned some stuff. The problem is that `crdbpgx` imports `pgx` as `github.com/jackc/pgx`. In order for crdbpgx to work with modules, it needs to import `pgx` as `github.com/jackc/pgx/v4`. Importing as `/v4`, of course, doesn't work when you're not using modules. Ugh.

The only solution I could come up with is to have a separate branch on the `cockroach-go` dedicated to module support. That branch will use `github.com/jackc/pgx/v4`, leaving the master branch as is. I've put a `v2.0.0` tag on the tip of the modules branch, so it can be imported from modules-aware code as `github.com/cockroachdb/cockroach-go/v2`. So, `import "github.com/cockroachdb/cockroach-go/v2/crdb/crdbpgx"`.
Would you mind updating your app to use that and telling me if it works for you?

**Comment by georgysavva** [comment]
I tested it from my app, it works. Thanks!
